"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const START_AT = new Date("2026-10-10T10:00:00+01:00").getTime();
const END_AT = new Date("2026-10-12T10:00:00+01:00").getTime();
const BOOT_LINES = ["initializing secure gateway...", "checking CTF protocol... [ok]", "recruitment channel open... [ok]"];
function remaining() { const ms = Math.max(0, START_AT - Date.now()); return { days: Math.floor(ms / 86400000), hours: Math.floor(ms / 3600000) % 24, minutes: Math.floor(ms / 60000) % 60, seconds: Math.floor(ms / 1000) % 60 }; }
const INITIAL_TIME = { days: 0, hours: 0, minutes: 0, seconds: 0 };
export default function GatePage() {
  const router = useRouter(); const [lines, setLines] = useState<string[]>([]); const [image, setImage] = useState<string>("/challenge-image.png"); const [answer, setAnswer] = useState(""); const [error, setError] = useState(""); const [checking, setChecking] = useState(false); const [solved, setSolved] = useState(false); const [hint, setHint] = useState(false); const [time, setTime] = useState(INITIAL_TIME);
  useEffect(() => { setTime(remaining()); const timer = setInterval(() => setTime(remaining()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { let i = 0; const timer = setInterval(() => { i += 1; setLines(BOOT_LINES.slice(0, i)); if (i === BOOT_LINES.length) clearInterval(timer); }, 350); return () => clearInterval(timer); }, []);
  useEffect(() => { fetch("/api/ctf/challenge").then((r) => r.json()).then((d) => { setImage(d.imageDataUrl); }).catch(() => setError("Unable to load the challenge.")); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!answer.trim() || checking) return; setChecking(true); setError(""); try { const r = await fetch("/api/ctf/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answer }) }); const d = await r.json(); if (!d.ok) setError(d.error); else { setSolved(true); setTimeout(() => router.push("/apply"), 900); } } catch { setError("Network error. Please try again."); } finally { setChecking(false); } }
  return <main className="min-h-screen flex items-center justify-center px-4 py-12"><div className="w-full max-w-3xl"><header className="flex items-center justify-between gap-4 mb-6"><div className="flex items-center gap-3"><img src="/logo.jpg" alt="ENISo CyberGuards" className="size-14 rounded-xl logo-glow" /><div><p className="text-xs text-cyan tracking-[0.25em]">ENISo CYBERGUARDS</p><p className="text-xs text-slate-400">recruitment · second call</p></div></div><div className="text-right hidden sm:block"><p className="text-[10px] uppercase tracking-widest text-slate-500">gateway status</p><p className="text-sm text-cyan">active from 10 October · 10:00</p></div></header>
    <section className="terminal-window rounded-2xl overflow-hidden"><div className="flex items-center gap-2 px-4 py-3 border-b border-slate-700 bg-slate-900/70"><span className="size-2.5 rounded-full bg-pink-400" /><span className="size-2.5 rounded-full bg-amber-300" /><span className="size-2.5 rounded-full bg-emerald-400" /><span className="ml-3 text-xs text-slate-400">root@cyberguards:~/second-call</span></div><div className="p-6 sm:p-9"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-5 mb-8"><div><div className="text-xs text-cyan mb-3">$ cat /etc/recruitment/status</div><h1 className="glitch-text text-2xl sm:text-4xl font-bold">The second call<span className="text-cyan">.</span></h1><p className="text-slate-400 mt-2 max-w-xl">A single signal is hidden in the image. Find it to unlock your application.</p></div><div className="grid grid-cols-4 gap-2 text-center">{Object.entries(time).map(([label, value]) => <div key={label} className="rounded-lg border border-slate-700 bg-slate-950/60 px-2 py-2 min-w-14"><div className="text-lg font-bold text-cyan tabular-nums">{String(value).padStart(2, "0")}</div><div className="text-[9px] uppercase text-slate-500">{label}</div></div>)}</div></div>
      {lines.map((line) => <p key={line} className="text-xs text-slate-500"><span className="text-cyan">$</span> {line}</p>)}
      <div className="mt-7 rounded-xl border border-slate-700 bg-slate-950/70 p-3 sm:p-4"><p className="text-xs text-slate-500 mb-3">// artefact_01.png · local analysis recommended</p>{image ? <img src={image} alt="Steganography challenge image" className="w-full rounded-lg border border-slate-800" /> : <div className="aspect-video animate-pulse rounded-lg bg-slate-900" />}</div>
      <div className="mt-5 text-sm text-slate-400"><p>The flag follows the format <code className="text-cyan">ECCC&#123;...&#125;</code>. The clue is hidden inside the image.</p><button type="button" className="mt-3 text-xs text-cyan underline underline-offset-4" onClick={() => setHint(!hint)}>{hint ? "hide hint" : "show hint"}</button>{hint && <p className="mt-2 border-l-2 border-cyan pl-3 text-xs text-slate-500">Every pixel matters in a picture. Download the image, run <code className="text-cyan">strings challenge-image.png</code>, and decode the hidden clue with any Base64 decoder. The decoded text reveals your dynamic flag.</p>}</div>
      <form onSubmit={submit} className="mt-6 flex flex-col sm:flex-row gap-3"><input value={answer} onChange={(e) => setAnswer(e.target.value)} className="field-input flex-1" placeholder="ECCC{...}" autoComplete="off" spellCheck={false} /><button disabled={checking || solved} className="rounded-lg border border-cyan bg-cyan/10 px-5 py-3 font-bold text-cyan transition hover:bg-cyan hover:text-slate-950 disabled:opacity-50">{solved ? "access granted ✓" : checking ? "checking..." : "unlock →"}</button></form>{error && <p className="mt-3 text-sm text-pink-400">✕ {error}</p>}
    </div></section><p className="text-center text-xs text-slate-500 mt-4">active from October 10, 10:00 · challenge is live</p></div></main>;
}
